# Generated by Django 5.0.3 on 2024-03-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='created_at',
            field=models.CharField(default='hello world', max_length=250),
            preserve_default=False,
        ),
    ]
